name: Build
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable & display version
        run: chmod +x ./gradlew && ./gradlew --version

      - name: Build & bundle
        run: ./gradlew bundle

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/quill/quill-template-bundle.zip # update accordingly
